# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 10:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Try not to exceed more than 50 characters (for aesthetic reasons).', max_length=200, verbose_name='Page Title')),
                ('slug', models.SlugField(unique=True)),
                ('header', models.BooleanField(default=True, help_text='Generic header with a background', verbose_name='Header with background image')),
                ('subheader', models.CharField(blank=True, help_text='This is the article title and should be a bit longer than the page title.', max_length=200, verbose_name='Tagline')),
                ('seo_keywords', models.CharField(blank=True, max_length=50, null=True, verbose_name='Meta Keywords')),
                ('seo_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta Description')),
                ('columns', models.CharField(choices=[('FULL', 'Full Width'), ('HALF', 'Two Columns')], default='FULL', max_length=4)),
                ('sidebar', models.BooleanField(default=False, verbose_name='Turn sidebar on?')),
                ('column_1', ckeditor.fields.RichTextField(help_text='This is left content box')),
                ('column_2', ckeditor.fields.RichTextField(blank=True, help_text="You don't have to fill this in if you have only one column")),
                ('sidebar_text', ckeditor.fields.RichTextField(blank=True, help_text='Sidebar Text if <b>Sidebar</b> is turned on')),
                ('cta', models.BooleanField(default=True, verbose_name='Call to Action Button?')),
                ('cta_text', models.CharField(blank=True, default='More News Articles', help_text='Default is: More News Articles', max_length=30, null=True, verbose_name='Button Text')),
                ('cta_url', models.CharField(blank=True, default='/news/', help_text='Within our site: /news/. External Site: https://google.com/', max_length=300, null=True, verbose_name='Button URL')),
                ('footer', models.BooleanField(default=True, verbose_name='Show Footer?')),
                ('socials', models.BooleanField(default=False, verbose_name='Social Icons?')),
                ('addthis_pubid', models.CharField(blank=True, help_text='This is the string that is AFTER `#pubid=`. Ex: ra-5a61fe428f3a39a8', max_length=25, null=True, verbose_name='AddThis PubId')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('published', models.BooleanField(default=False, help_text='Unpublished pages are only visible to admins.', verbose_name='Publish Page?')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
            },
        ),
    ]
